### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "u1001",
    "password": "changeit",
    "role": "USER"
}

### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "u1006",
    "password": "changeit",
    "role": "USER"
}

### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "u1005",
    "password": "changeit",
    "role": "APPROVER"
}

### auth login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "u1006",
    "password": "changeit"
}

###
### Admin Zone
###
### create
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "a1001",
    "password": "changeit",
    "role": "ADMIN"
}